### ISSUE TITLE
Some bugs about mol_graph.py

### ISSUE THREAD

**Issue by ClinuxMDL** [HIPS/neural-fingerprint#1]
Hello,

I have met a bug about 

********************************************
mol_graph.py", line 79, in graph_from_smiles
    raise ValueError("Could not parse SMILES string:", smiles)
ValueError: ('Could not parse SMILES string:', 'CCCCCCCCCCCC[N](C)(C)CC(=O)O')"
***************************************************************************************

As described above, the "[N]" in the smiles couldn't be parsed. I wonder if this question is mainly due to the limitation of rdkit package. 
Or would you have any better solutions about this bug?

Best regards,
YJ

**Comment by t1m0thy** [comment]
This is definitely pure rdkit.  

To try directly:

    import rdkit.Chem.AllChem as Chem

    Chem.MolFromSmiles(your_str)


Writing in my phone so maybe a bug or typo in there.   

Hope that helps,
Tim

**Comment by ClinuxMDL** [comment]
Dear Tim,

Thank you very much.  

Best regards,
YJ
