### ISSUE TITLE
Malari Dataset

### ISSUE THREAD

**Issue by yuanjames** [HIPS/neural-fingerprint#11]
Hi, I am wondering that malaria dataset is from real experiments or calculation?

**Comment by duvenaud** [comment]
It's explained in the paper, they're from in vitro experiments.

**Comment by yuanjames** [comment]
Hi, thanks for your explanation. I noticed the paper mentioned the size of malaria data is 10000, but in processed-malaria only has 9999, and raw data is 20476. Did you sample 10000 data points from 20476?

**Comment by duvenaud** [comment]
Yes, take a look at https://github.com/HIPS/neural-fingerprint/blob/master/data/2015-06-03-malaria/preprocess_data.py#L18

**Comment by yuanjames** [comment]
> Yes, take a look at https://github.com/HIPS/neural-fingerprint/blob/master/data/2015-06-03-malaria/preprocess_data.py#L18

Thanks a lot!
