### ISSUE TITLE
experiment scripts import error

### ISSUE THREAD

**Issue by fgvbrt** [HIPS/neural-fingerprint#5]
Hello, 
I was trying to launch script launch_experiments.py in directory experiment_scripts and got error:
Traceback (most recent call last):
  File "launch_experiments.py", line 11, in <module>
    from nfpexperiment import util
ImportError: No module named nfpexperiment

It seesm that there is not module nfpexperiment. Could you please provide this module?
Thanks in advance.

**Comment by duvenaud** [comment]
Sorry, I think there are a lot of things you'd have to do to get those experiment scripts running.  I just added them so people could see which hyperparameter ranges we used in the experiments for the paper.

**Comment by platinhom** [comment]
@duvenaud Hi Dr. Duvenaud, can you help to offer the relative experiment scripts to repeat the results?  Thanks

**Comment by duvenaud** [comment]
Ok I added the nfpexperiment module, it was just a couple of helper functions for loading results.  Hope this helps!
