### ISSUE TITLE
The metrics of Mean predictive accuracy of neural fingerprints in table 1

### ISSUE THREAD

**Issue by xiongzhp** [HIPS/neural-fingerprint#8]
Is the metric MAE, MSE or RMSE?

**Comment by duvenaud** [comment]
To be honest, I'm not sure :/  I think it was MSE.  The good news is that you can fairly easily check by computing the error that you would get by predicting the mean, and comparing that to the first row of the table.

**Comment by xiongzhp** [comment]
Thanks! It was MSE, but some followers mistake it as RMSE.

**Comment by duvenaud** [comment]
Thanks for checking!  Ach, that's an unfortunate confusion, and it's my fault.  I should fix that omission.
